import type { PieceMeta } from "./types";

/** Client-safe catalogue — titles and teasers. Full text is in the chapter files. */
export const CATALOG: PieceMeta[] = [
  {
    slug: "21-hutton-lane",
    kind: "chapter",
    kicker: "Chapter 01",
    title: "21 Hutton Lane",
    dek: "My first clear memory is my uncle Keith knocking the fireplace out of the wall at 21 Hutton Lane.",
    readMins: 3,
    free: true,
    order: 1,
  },
  {
    slug: "taken-at-eight",
    kind: "chapter",
    kicker: "Chapter 02",
    title: "Taken at Eight",
    dek: "I do not remember being told.",
    readMins: 3,
    free: true,
    order: 2,
  },
  {
    slug: "carol",
    kind: "chapter",
    kicker: "Chapter 03",
    title: "Carol",
    dek: "After the removal the violence and the damage began in earnest.",
    readMins: 2,
    free: true,
    order: 3,
  },
  {
    slug: "steven",
    kind: "chapter",
    kicker: "Chapter 04",
    title: "Steven",
    dek: "My father, Steven Hostettler.",
    readMins: 2,
    free: true,
    order: 4,
  },
  {
    slug: "hatch-end",
    kind: "chapter",
    kicker: "Chapter 05",
    title: "Hatch End",
    dek: "By thirteen I was at Hatch End High School.",
    readMins: 2,
    free: true,
    order: 5,
  },
  {
    slug: "chelsea",
    kind: "chapter",
    kicker: "Chapter 06",
    title: "Chelsea",
    dek: "The babysitter in Hayes.",
    readMins: 1,
    free: true,
    order: 6,
  },
  {
    slug: "tent-by-the-lake",
    kind: "chapter",
    kicker: "Chapter 07",
    title: "The Tent by the Lake",
    dek: "After Chelsea the streets and the temporary places became more permanent.",
    readMins: 2,
    free: true,
    order: 7,
  },
  {
    slug: "cardboard-offices",
    kind: "chapter",
    kicker: "Chapter 08",
    title: "Cardboard Offices and the Cadets",
    dek: "Long before the tent and the burglaries there had been the early signs of how my mind worked.",
    readMins: 2,
    free: true,
    order: 8,
  },
  {
    slug: "older-company",
    kind: "chapter",
    kicker: "Chapter 09",
    title: "Older Company \u2014 The Painting, Straff and Gadget",
    dek: "I was about seventeen and already wrapped up with serious people.",
    readMins: 5,
    free: true,
    order: 9,
  },
  {
    slug: "uncle-pat",
    kind: "chapter",
    kicker: "Chapter 10",
    title: "Uncle Pat",
    dek: "Patrick McCann.",
    readMins: 2,
    free: true,
    order: 10,
  },
  {
    slug: "stonebridge",
    kind: "chapter",
    kicker: "Chapter 11",
    title: "Stonebridge and the Trade",
    dek: "The two brothers from Stonebridge were the entry point.",
    readMins: 3,
    free: true,
    order: 11,
  },
  {
    slug: "what-ive-built",
    kind: "chapter",
    kicker: "Chapter 12",
    title: "What I\u2019ve Built With Nothing",
    dek: "Everything before this chapter is about what was taken.",
    readMins: 3,
    free: true,
    order: 12,
  },
  {
    slug: "five-years-clean",
    kind: "chapter",
    kicker: "Chapter 13",
    title: "Five Years Clean and the Present Body",
    dek: "I have been clean from heroin for over five years.",
    readMins: 3,
    free: true,
    order: 13,
  },
  {
    slug: "the-names-that-do-not-leave",
    kind: "chapter",
    kicker: "Chapter 14",
    title: "The Names That Do Not Leave",
    dek: "The names from the older generation never fully leave.",
    readMins: 1,
    free: true,
    order: 14,
  },
  {
    slug: "dual-names",
    kind: "chapter",
    kicker: "Chapter 15",
    title: "Dual Names and the Public Record",
    dek: "In Poland there is a birth certificate under one name.",
    readMins: 1,
    free: true,
    order: 15,
  },
  {
    slug: "the-record",
    kind: "chapter",
    kicker: "Chapter 16",
    title: "The Record",
    dek: "I have been clean five years.",
    readMins: 1,
    free: true,
    order: 16,
  },
  {
    slug: "the-claims-and-the-record",
    kind: "chapter",
    kicker: "Chapter 17",
    title: "The Claims and the Record",
    dek: "In the late summer of 2026 a conversation began that stretched across multiple sessions and dozens of specific assertions.",
    readMins: 6,
    free: true,
    order: 17,
  },
  {
    slug: "salisbury-porton-down",
    kind: "chapter",
    kicker: "Chapter 18",
    title: "Salisbury, Porton Down and the Claims",
    dek: "You asked for an article on the \u201cfacts\u201d around Salisbury and the Porton Down bio lab being breached.",
    readMins: 2,
    free: true,
    order: 18,
  },
  {
    slug: "e-paper",
    kind: "article",
    kicker: "Dispatch",
    title: "The E-Paper",
    dek: "Why this edition is a paper you can put in a pocket, not a feed you fall into.",
    readMins: 2,
    free: true,
    order: 101,
  },
  {
    slug: "notes-from-the-desk",
    kind: "article",
    kicker: "Notebook",
    title: "Notes from the Desk",
    dek: "How an edition is assembled when the night editor is the person who also walked the route.",
    readMins: 2,
    free: false,
    order: 102,
  },
  {
    slug: "url-not-a-shop",
    kind: "article",
    kicker: "Format",
    title: "A URL, Not a Shop",
    dek: "Publish where it cannot be banned from the shelf.",
    readMins: 3,
    free: false,
    order: 103,
  },
  {
    slug: "invite",
    kind: "article",
    kicker: "Studio",
    title: "Invite to the Studio",
    dek: "Builders welcome. Jealousy is not a credential.",
    readMins: 3,
    free: false,
    order: 104,
  },
];

export function getMeta(slug: string): PieceMeta | undefined {
  return CATALOG.find((p) => p.slug === slug);
}

export const CHAPTERS = CATALOG.filter((p) => p.kind === "chapter");
export const ARTICLES = CATALOG.filter((p) => p.kind === "article");
export const FREE_SLUGS = new Set(CATALOG.filter((p) => p.free).map((p) => p.slug));
